-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\L3G4200D_SPI\Wrap_To_Zero_block.vhd
-- Created: 2015-04-14 21:31:24
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Wrap_To_Zero_block
-- Source Path: L3G4200D_SPI/hdl_dut/Incremental Counter1/Wrap To Zero
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Wrap_To_Zero_block IS
  PORT( U                                 :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Y                                 :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
        );
END Wrap_To_Zero_block;


ARCHITECTURE rtl OF Wrap_To_Zero_block IS

  -- Signals
  SIGNAL U_unsigned                       : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant_out1                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL FixPt_Switch_out1                : unsigned(15 DOWNTO 0);  -- uint16

BEGIN
  U_unsigned <= unsigned(U);

  
  switch_compare_1 <= '1' WHEN U_unsigned > to_unsigned(16#0006#, 16) ELSE
      '0';

  Constant_out1 <= to_unsigned(16#0000#, 16);

  
  FixPt_Switch_out1 <= U_unsigned WHEN switch_compare_1 = '0' ELSE
      Constant_out1;

  Y <= std_logic_vector(FixPt_Switch_out1);


END rtl;

