vlib work
vcom  hdl_dut_pkg.vhd
vcom  Control_Signals.vhd
vcom  rising_edge_detect.vhd
vcom  shiftRegister_48.vhd
vcom  XYZ_shiftRegister.vhd
vcom  Read_X_Y_Z.vhd
vcom  Write.vhd
vcom  ADXL345_read.vhd
vcom  Calculate_f_coeff.vhd
vcom  Chart.vhd
vcom  PWM_Motor1.vhd
vcom  Calculate_f_coeff_block.vhd
vcom  PWM_Motor2.vhd
vcom  Calculate_f_coeff_block1.vhd
vcom  PWM_Motor3.vhd
vcom  Calculate_f_coeff_block2.vhd
vcom  PWM_Motor4.vhd
vcom  hdl_dut.vhd
