# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_constraint.xdc

# Block Designs: bd/System/System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System}]

# IP: bd/System/ip/System_axi_interconnect_0_0/System_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_interconnect_0_0 || ORIG_REF_NAME==System_axi_interconnect_0_0}]

# IP: bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_clk_wiz_0_0 || ORIG_REF_NAME==System_clk_wiz_0_0}]

# IP: bd/System/ip/System_proc_sys_reset_0_0/System_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_proc_sys_reset_0_0 || ORIG_REF_NAME==System_proc_sys_reset_0_0}]

# IP: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}]

# IP: bd/System/ip/System_BasicQuadrotorControlv2_hdl_dut_ipcore_0_0/System_BasicQuadrotorControlv2_hdl_dut_ipcore_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_BasicQuadrotorControlv2_hdl_dut_ipcore_0_0 || ORIG_REF_NAME==System_BasicQuadrotorControlv2_hdl_dut_ipcore_0_0}]

# IP: bd/System/ip/System_auto_pc_0/System_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_0 || ORIG_REF_NAME==System_auto_pc_0}]

# XDC: bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_clk_wiz_0_0 || ORIG_REF_NAME==System_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_ooc.xdc

# XDC: bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_clk_wiz_0_0 || ORIG_REF_NAME==System_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_proc_sys_reset_0_0/System_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_proc_sys_reset_0_0 || ORIG_REF_NAME==System_proc_sys_reset_0_0}]

# XDC: bd/System/ip/System_proc_sys_reset_0_0/System_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/System/ip/System_proc_sys_reset_0_0/System_proc_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_proc_sys_reset_0_0 || ORIG_REF_NAME==System_proc_sys_reset_0_0}]

# XDC: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/System/ip/System_auto_pc_0/System_auto_pc_0_ooc.xdc

# XDC: bd/System/System_ooc.xdc
