# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths C:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/ipcore [current_fileset]

add_files C:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/System.bd
set_property used_in_implementation false [get_files -all c:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/ip/System_proc_sys_reset_0_0/System_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/ip/System_proc_sys_reset_0_0/System_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/ip/System_proc_sys_reset_0_0/System_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/ip/System_auto_pc_0/System_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/System_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files C:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/System.bd]

read_vhdl -library xil_defaultlib C:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.srcs/sources_1/bd/System/hdl/System_wrapper.vhd
read_xdc C:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_constraint.xdc
set_property used_in_implementation false [get_files C:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_constraint.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj/vivado_prj.cache/wt [current_project]
set_property parent.project_dir C:/Projects/QuadRotorProject/work/hdl_prj/vivado_ip_prj [current_project]
catch { write_hwdef -file System_wrapper.hwdef }
synth_design -top System_wrapper -part xc7z020clg400-1
write_checkpoint System_wrapper.dcp
report_utilization -file System_wrapper_utilization_synth.rpt -pb System_wrapper_utilization_synth.pb
