%% Product Guide
% This page is generated by HDL Coder for IP core:
% L3G4200D_SPI_hdl_dut_ipcore.
% 
% Please open the IP Core Generation Report using following link:
% 
% <file://L3G4200D_SPI_ip_core_report.html doc/L3G4200D_SPI_ip_core_report.html>
