-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\BasicQuadrotorControl\Control_Signals.vhd
-- Created: 2015-02-18 16:12:25
-- 
-- Generated by MATLAB 8.4 and HDL Coder 3.5
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Control_Signals
-- Source Path: BasicQuadrotorControl/hdl_dut/ADXL345_read/Control_Signals
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Control_Signals IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        WCS                               :   IN    std_logic;
        WSCLK                             :   IN    std_logic;
        WEN                               :   IN    std_logic;
        WSDI                              :   IN    std_logic;
        RCS                               :   IN    std_logic;
        RSCLK                             :   IN    std_logic;
        REN                               :   IN    std_logic;
        RSDI                              :   IN    std_logic;
        CS                                :   OUT   std_logic;
        SCLK                              :   OUT   std_logic;
        SDI                               :   OUT   std_logic
        );
END Control_Signals;


ARCHITECTURE rtl OF Control_Signals IS

  -- Signals
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable_zero_delay : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable_switch_delay : std_logic;  -- ufix1
  SIGNAL Unit_Delay_Enabled_Resettable_1  : std_logic;
  SIGNAL Unit_Delay_Enabled_Resettable_out1 : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Switch_out1                      : std_logic;
  SIGNAL switch_compare_1_1               : std_logic;
  SIGNAL Switch1_out1                     : std_logic;
  SIGNAL switch_compare_1_2               : std_logic;
  SIGNAL Switch2_out1                     : std_logic;

BEGIN
  Constant_out1 <= '1';

  Unit_Delay_Enabled_Resettable_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay_Enabled_Resettable_zero_delay <= '1';
      Unit_Delay_Enabled_Resettable_switch_delay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay_Enabled_Resettable_zero_delay <= '0';
        IF REN = '1' THEN 
          Unit_Delay_Enabled_Resettable_switch_delay <= '0';
        ELSIF WEN = '1' THEN 
          Unit_Delay_Enabled_Resettable_switch_delay <= Constant_out1;
        ELSE 
          Unit_Delay_Enabled_Resettable_switch_delay <= Unit_Delay_Enabled_Resettable_out1;
        END IF;
      END IF;
    END IF;
  END PROCESS Unit_Delay_Enabled_Resettable_process;
  
  Unit_Delay_Enabled_Resettable_1 <= '1' WHEN (REN OR Unit_Delay_Enabled_Resettable_zero_delay) = '1' ELSE
      '0';
  
  Unit_Delay_Enabled_Resettable_out1 <= '0' WHEN Unit_Delay_Enabled_Resettable_1 = '1' ELSE
      Unit_Delay_Enabled_Resettable_switch_delay;

  
  switch_compare_1 <= '1' WHEN Unit_Delay_Enabled_Resettable_out1 > '0' ELSE
      '0';

  
  Switch_out1 <= RCS WHEN switch_compare_1 = '0' ELSE
      WCS;

  
  switch_compare_1_1 <= '1' WHEN Unit_Delay_Enabled_Resettable_out1 > '0' ELSE
      '0';

  
  Switch1_out1 <= RSCLK WHEN switch_compare_1_1 = '0' ELSE
      WSCLK;

  
  switch_compare_1_2 <= '1' WHEN Unit_Delay_Enabled_Resettable_out1 > '0' ELSE
      '0';

  
  Switch2_out1 <= RSDI WHEN switch_compare_1_2 = '0' ELSE
      WSDI;

  CS <= Switch_out1;

  SCLK <= Switch1_out1;

  SDI <= Switch2_out1;

END rtl;

