-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\BasicQuadrotorControl\hdl_dut_pkg.vhd
-- Created: 2015-02-18 16:12:25
-- 
-- Generated by MATLAB 8.4 and HDL Coder 3.5
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE hdl_dut_pkg IS
  TYPE T_state_type_is_Chart IS (IN_HIGH, IN_LOW, IN_S1, IN_S2);
  TYPE T_state_type_is_Read_X_Y_Z IS (IN_CLOCKING, IN_END, IN_IDLE, IN_Read, IN_Read1, IN_START_ADC_RDWR, IN_START_CONV, IN_tCONV_delay);
  TYPE T_state_type_is_Write IS (IN_CLOCKING, IN_END, IN_END1, IN_IDLE, IN_START_ADC_RDWR, IN_START_CONV, IN_tCONV_delay);
END hdl_dut_pkg;

