-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\L3G4200D_SPI\hdl_dut_pkg.vhd
-- Created: 2015-04-14 21:31:24
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE hdl_dut_pkg IS
  TYPE T_state_type_is_READ IS (IN_NO_ACTIVE_CHILD, IN_CLK_END1, IN_CLOCK_BEGIN1, IN_CLOCK_HIGH1, IN_CLOCK_HIGH3, IN_CLOCK_LOW1, IN_CLOCK_LOW3, IN_DATA_VALID1);
  TYPE T_state_type_is_Transmit IS (IN_BEGIN, IN_CHIPSELECT, IN_END_TRANS, IN_IDLE, IN_READ, IN_STALL, IN_WRITE);
  TYPE T_state_type_is_WRITE IS (IN_NO_ACTIVE_CHILD, IN_CLOCK_BEGIN, IN_CLOCK_END, IN_CLOCK_HIGH, IN_CLOCK_LOW);
  TYPE vector_of_unsigned16 IS ARRAY (NATURAL RANGE <>) OF unsigned(15 DOWNTO 0);
  TYPE vector_of_signed8 IS ARRAY (NATURAL RANGE <>) OF signed(7 DOWNTO 0);
END hdl_dut_pkg;

