vlib work
vcom  hdl_dut_pkg.vhd
vcom  Detect_Increase1.vhd
vcom  Detect_Increase1_block.vhd
vcom  Wrap_To_Zero.vhd
vcom  Incremental_Counter.vhd
vcom  Detect_Increase1_block1.vhd
vcom  Wrap_To_Zero_block.vhd
vcom  Incremental_Counter1.vhd
vcom  Initialized_Check.vhd
vcom  Transmit.vhd
vcom  hdl_dut.vhd
