-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\L3G4200D_SPI\Initialized_Check.vhd
-- Created: 2015-04-14 21:31:24
-- 
-- Generated by MATLAB 8.5 and HDL Coder 3.6
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Initialized_Check
-- Source Path: L3G4200D_SPI/hdl_dut/Initialized Check
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Initialized_Check IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        in_rsvd                           :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        out_rsvd                          :   OUT   std_logic
        );
END Initialized_Check;


ARCHITECTURE rtl OF Initialized_Check IS

  -- Signals
  SIGNAL in_unsigned                      : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL init_complete_not_empty          : std_logic;
  SIGNAL init_complete_not_empty_next     : std_logic;

BEGIN
  in_unsigned <= unsigned(in_rsvd);

  Initialized_Check_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      init_complete_not_empty <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        init_complete_not_empty <= init_complete_not_empty_next;
      END IF;
    END IF;
  END PROCESS Initialized_Check_1_process;

  Initialized_Check_1_output : PROCESS (in_unsigned, init_complete_not_empty)
  BEGIN
    init_complete_not_empty_next <= init_complete_not_empty;
    IF ( NOT init_complete_not_empty) = '1' THEN 
      IF in_unsigned = to_unsigned(16#0003#, 16) THEN 
        -- Init after first data has been sent
        out_rsvd <= '0';
        init_complete_not_empty_next <= '1';
      ELSE 
        out_rsvd <= '0';
      END IF;
    ELSE 
      out_rsvd <= '1';
    END IF;
  END PROCESS Initialized_Check_1_output;


END rtl;

